#!/usr/bin/env bash
# a Bash script that install Nginx on a server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root    /var/www/html;
    index   index.nginx-debian.html;
    location /redirect_me {
	    return 301 http://youtube.com/;
}
}" > /etc/nginx/sites-available/default
sudo service nginx restart
