#!/usr/bin/env bash
# Recdirect 404 error to a custom file whit the string Ceci n'est pas une page.

sudo apt-get update
sudo apt-get install -y nginx

# Create default page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Firewall Configurate server
#ufw allow 'Nginx HTTP'

f_config="/etc/nginx/sites-available/default"
# Add redirection
new_site="https://github.com/Alltoft"
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new_site permanent;" $f_config

# Add 404 redirection
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/my_404.html
new_404="my_404.html"
l_new_404="/my_404.html {root /usr/share/nginx/html;\n internal;}"
sudo sed -i "/listen 80 default_server/a error_page 404 /$new_404; location = $l_new_404" $f_config

sudo service nginx restart
