#!/usr/bin/env bash
# a Bash script that displays Best School 10 times
i=0
while ((i <= 20)); do
    case $i in
        5)
            echo "bad luck from China"
            ;;
        10)
            echo "bad luck from Japan"
            ;;
        18)
            echo "bad luck from Italy"
            ;;
        *)
            echo "$i"
    esac
    ((i++))
done
