#!/usr/bin/env bash
#install and config a firewall

sudo apt install ufw
sudo ufw disable
sudo ufw default deny incomming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 433/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status
